"""Author and archive the slice's production briefs before image generation."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STYLE = "OPAQUE WHITE PAPER BACKGROUND, fully opaque RGB image with solid white #FFFFFF in every empty region, including between limbs. No transparency or alpha channel, gradient, vignette or halo. Use case: stylized-concept. LATTICE production design. Crisp cel-shaded anime game art with restrained flat local-color regions and readable silhouettes. Even unshadowed studio illumination. No gloss, specular highlights, reflections, rim light, cast shadows, ground shadows, ambient occlusion, bloom spill, scenery, floor, particles, text, labels, watermark, borders or detached decorative parts. Emissive lines are opaque saturated color, not illumination. Every appendage is visibly rooted in its body."
SINGLE = "Exactly ONE isolated complete subject, ONE view only, filling 80-88 percent of the canvas with clear margin on every side. No inset, turnaround, duplicate, cropped appendage or ground plane. This image will be reconstructed into 3D."
VAEL = "Vael alien anatomy: smooth matte slate skin and a lighter face/throat/palms, plantigrade biped, no tail, no external ears, no hair, no fur or scales. Swept-back elongated cranium, low sensory ridge behind jaw, soft low-bridge nose, almond eyes with readable pale sclera and ring irises. Crown/back crest consists of thick flat overlapping keratin FRONDS, not hair strands. Branching sync-lines run temple to jaw, collar to sternum, elbow to hand and knee to shin. Four fingers plus thumb per hand; all five separated. Forearm 1.06-1.12 times upper arm. Body 7.2-7.6 heads tall, adult 1.85-1.95m. Natural forms wear muted asymmetric wraps over a fitted underlayer with collar node, two wrist bands and a spine docking plate. Practical trousers stop short of feet: no long skirt bridging legs."
POSE = "Single straight orthographic FRONT view, face aimed exactly with torso, calm closed mouth, neutral relaxed A pose: arms 30-40 degrees away from sides, palms forward, five relaxed separated digits with visible white gaps. Feet parallel, shoulder width apart. Unbroken wide white gaps between both arms and trunk, between legs from crotch down, between fingers, and around accessories. Wraps stay on the torso or their own leg and never bridge legs. No held props."
NPCS = {
 "orrin": "Orrin Malk, mature male dockmaster, broad rectangular face, broad flattened nose, heavy low brow, tired hooded green ring eyes, wide square jaw, closed fond frown. Short cropped stone-grey keratin plumes #7C858D; slate-grey skin #667681, face #98A5AA, restrained dim-green sync-lines #49BE87. Deep navy underlayer #26384A, slate-beige asymmetric dock-office wraps #8C8C7D and one muted green sash #487764. Shoulder width 1.22-1.30 hip width; waist 0.90-0.98 hip width. Clearly older, broader and more grounded than Taren; no beard or human ears.",
 "mira": "Mira Tessen, adult female outfitter, rounded heart-shaped face, full cheek pads, short broad nose, arched brow ridges, large alert orange ring eyes, small asymmetric saleswoman's smile. Rust-red flat keratin plume-mane #A34D36, slate skin #7E838C, face #ACAFB2, orange sync-lines #FF913D. Aubergine underlayer #403C51, sand wraps #AF9B7B and terracotta sash #A95E41. Shoulder width 0.99-1.06 hip width; waist 0.85-0.93 hip width. Fronds end near shoulder blades and stay behind outspread arms. Solid practical physique, no exaggerated sexual anatomy. Distinct from narrow-faced Sela.",
 "hal": "Hal Quen, older male repairer, long broad face, soft round jaw, gentle deep-set blue ring eyes, broad rounded low nose, subtle cheek folds. Pale ivory-grey short thick keratin plumes #C9C9B9 with one conspicuous gap in the upper left crest where a frond is missing. Warm-grey skin #7A8284, light face #A5ABAA, blue sync-lines #388DFF. Charcoal underlayer #303D46, weathered ochre asymmetric short workshop wraps #A49368, blue sash #507DA0; pockets sewn flat, no tools or dangling parts. Shoulder width 1.19-1.27 hip width; waist 0.93-1.00 hip width. Distinct long gentle face from Orrin's square face.",
 "neve": "Neve, adult female pilot, narrow diamond face, high angular cheeks, long but low-bridge nose, narrow restless white-ring eyes, slanted brow ridges, thin lips with a slight crooked smile. Black keratin plume-mane #222D39 with blue-grey roots #3C4B5C. Slate-blue skin #657B8D, face #93ABBA, thin white sync-lines #F1F7FC. Deep midnight underlayer #273547, asymmetric blue-grey short pilot wraps #607C91 and pale accent sash #AFBCC7. Shoulder width 1.00-1.08 hip width; waist 0.87-0.94 hip width. Long swept fronds reach shoulder blades behind the arms; all still clearly separate from hands. Athletic practical build, distinct from round-faced Mira.",
}
ENEMIES = {
 "sentinel-husk": "Sentinel Husk, 2.4m tall armoured BIPED relic; readable humanoid head-neck-torso-hips and two arms/two legs, not a quadruped. Broad blunt octagonal shoulders, compact visor head, oversized shield-like left forearm, right piledriver fist. Dark basalt #394651 segmented armour with dusty ochre inset plates #A6946A and thin saturated cyan #22F5FF seams. Width-to-height 0.36-0.43; neck visible above torso. It must NOT resemble the low ridgehound, tiny scrapmite or round burrower: its upright shield silhouette is its identity. Front A-pose, head forward, arms 35 degrees off trunk, fists unclenched, legs shoulder-width with wide white gaps. Five stubby separated fingers on each hand; armour attached to its own limb only. Single orthographic front view.",
 "ridgehound": "Ridgehound, alien QUADRUPED pack predator, 2.2m nose-to-tail, shoulder height 0.75-0.90m, lean low dog-like body with four separate digitigrade legs and three blunt toes per paw, no hands or humanoid torso. Identity: a low wedge head with three rooted backward-swept rust basalt crest plates and sharply sloped armoured shoulders. Dusty russet #995E45 dorsal armour, charcoal #3D464B lower body, small lime #AACF5A eye/side fissures. Not a wolf in fur, not round like Burrower, not a six-legged Scrapmite. Short thick tail extended straight back, separated from rump contour beyond its root and never touching legs. Single orthographic three-quarter FRONT view about 35 degrees. Stagger near front foot half a head forward of far front foot, hind legs also staggered; broad continuous white between all four legs. Head aligned with body; every paw fully visible, no resting on ground.",
 "scrapmite": "Scrapmite, small low SIX-LEGGED mechanical scavenger 0.45-0.55m long, squat hexagonal body, three segmented short legs per side. Six grounded attachment roots with background between every leg from first joint outward; legs never cross each other. Identity is a rusty angular broken circuit carapace and one bright amber #FFB62E central eye, dark grey #464F54 and copper #B77547 plates. Width 0.75-0.90 body length. It must NOT read as four-legged Ridgehound, round Shellmine or a flying Chorister: all six little skitter legs plainly counted. Single orthographic three-quarter front view 30 degrees above, no loose scrap or debris.",
 "burrower": "Burrower, large limbless alien drilling grub mini-boss, 5-6m long, diameter 0.30-0.38 length. Identity: thick curved segmented ochre #9C754F carapace, blunt three-petal rock auger face fixed open around a dark maw, bright beam-vulnerable turquoise #22F5FF throat. Five heavy linked body rings taper to a blunt tail; each ring overlaps the next as one continuous body, no detached sections. No legs, arms, fur, wings or extra tentacles. Body nearly straight with slight upward head arch, head aligned with body. Must NOT resemble thin flying Cantor: stocky earth-drilling body and massive round drill head. Single orthographic three-quarter front view 35 degrees with complete tail and visible full length.",
 "chorister-dart": "Chorister Dart, small flying alien 0.8-1.0m long, a narrow spear-shaped violet #635B88 body with one small orange #FFAB68 eye and two swept pointed fins visibly attached by distinct narrow roots. Fin tip span 0.60-0.78 body length. Rear taper like a needle. No legs, feathers, beak or humanoid face. Continuous cyan #22F5FF organ seams. The identity is a sharp triangular dive-bomber silhouette, unlike a round Drifter, blunt Shellmine or segmented Cantor. Single orthographic three-quarter front view 30 degrees above; white triangles separate each attached fin from central body along its trailing edge, no detached fins.",
 "chorister-drifter": "Chorister Drifter, floating alien spitter 1.3-1.6m wide, a flattened bell-shaped mauve #8B6D98 carapace, three large forward nozzle mouths integrated into its underside and five short thick hanging tendrils attached around rim. Each tendril 0.24-0.32 bell diameter, thick enough for reconstruction, gently curved downward with generous white gaps and no intersections. Dark indigo #354569 underside; cyan #22F5FF seam rings and coral #E9978D nozzle lips. No smoke, goo, bubbles or free floating parts. Its identity is a broad bell with three firing throats: must NOT resemble the sharp Dart, spiked Shellmine or long Cantor. Single orthographic three-quarter front view at eye height.",
 "shellmine": "Shellmine, stationary alien proximity mine 0.8-1.0m diameter, compact dark indigo #3A4665 spherical shell flattened beneath, six short thick blunt conical spikes in a radial star, each attached at its own base with visible white between neighbouring spikes. Bright coral #EE8174 central hexagonal iris and cyan #22F5FF seam ring. Small integral triangular mounting foot, not a scenic base. No legs, tendrils, wings or detached shards. Must NOT read as bell-shaped Drifter or tiny six-legged Scrapmite; a closed spiked sea-urchin shell. Single orthographic three-quarter front view 20 degrees above.",
 "cantor": "Cantor boss concept, ONE entire long segmented alien SERPENT 22-26m long, head width 0.08-0.11 total length, seven visibly connected body segments and a tapered leaf-like tail. Dark blue #344D6E and violet #77689B hard organic armour; three body sections carry clear circular coral #F29481 weak-point organs framed in saturated cyan #22F5FF. Wedge-shaped crown head with two swept attached cheek fins and a gaping three-slot resonator mouth. No arms, legs, hair or ground. Gently rising shallow S curve, all segments touch along a central continuous spine, no self-overlap, complete side contour readable. It must NOT resemble stocky Burrower or a winged dragon: a long narrow flying choir serpent. Single orthographic three-quarter front view about 25 degrees; no extra views or detached diagram parts.",
}
SHIPS = {
 "hauler": "Vael civilian cargo HAULER, 22-28m long, broad smooth rounded hull with two integrated cargo lobes and a low central cockpit. Width 0.46-0.56 length. Matte warm ivory #C4BBA8 plating, slate #465563 recesses, burnt orange #B87951 bands, thin cyan #22F5FF Lattice seams. Twin rear thrust apertures are dark, no exhaust. Three connected masses, no loose containers. Must read as broad workhorse compared with tiny needle Skiff and angular twin-prong Cutter.",
 "skiff": "Vael personal SKIFF, 5-7m long, smooth narrow teardrop fuselage with small swept attached side vanes and single cockpit, width 0.28-0.36 length. Matte slate-blue #617C92, cream #C5CFCE underside, cyan #22F5FF Lattice seams. One central rear thrust socket, no exhaust. Minimal compact silhouette, clearly narrower than the heavy Hauler and without the Cutter's twin prongs.",
 "cutter": "Vael patrol CUTTER, 13-17m long, smooth central hull splitting into two attached forward prongs with a wide white slot between them, width 0.37-0.45 length. Matte charcoal #364959, pale grey #A8BCBE armor and cyan #22F5FF Lattice seams. Compact central cockpit. Two integral rear thrust sockets, no exhaust. Swept shoulder guards stay attached. Sharper bifurcated patrol silhouette than rounded Hauler or teardrop Skiff.",
}
ENV = {
 "sorrel-environment-board": "A clean design board arranged as TEN separated object cells in two rows of five, each object is ONE three-quarter view. Contents in reading order: (1) flat dusty ochre square ground tile with fine grit, (2) square rocky ground tile with broad fractured slabs, (3) tall thin layered ridge rock, (4) wide arch-free ridge boulder, (5) three-step ridge shelf, (6) rooted cyan crystal cluster with three thick distinct prongs and clear gaps, (7) rooted cyan crystal cluster with five shorter separated prongs, (8) low Lattice Anvil with a cyan inset work slot and broad integral base, (9) compact rounded outpost hab module with door and asymmetric roof vent, (10) outpost drill with thick attached vertical mast and rooted drill bit. Then a separate broad circular landing-pad design shown as a modest eleventh cell beneath the two rows. Materials dusty warm #A88461 rock, dark slate #485568 outpost plating, small cream accents, cyan #22F5FF seams. Every cell isolated on white with substantial gutters, all pieces matte and connected; no terrain scene or characters. This is a design board, NOT a model input.",
 "halo-environment-board": "Six separated concept cells in two rows of three, ONE three-quarter view per cell, large white gutters: (1) curved smooth Cinder Halo ring segment with narrow window ribbon and cyan Lattice seams; (2) alternative ring segment with a structural arch and outer docking lip; (3) rounded office docking pod with simple recessed door and tall signal fin; (4) outfitter pod with broad window and horizontal canopy; (5) repair pod with large open service mouth and two integrated clamps; (6) free-standing warp beacon, tall continuous split arch with both prongs attached to one thick base. Matte warm ivory #C6BEA9, slate #4C5B68, copper #B17B51, cyan #22F5FF lines. Smooth inhabited civil architecture, NOT military block fortresses. No planetary backdrop, letters, labels or lights floating free. This is a design board, NOT a model input.",
 "decks-environment-board": "Six separated concept cells in two rows of three, ONE three-quarter view per cell: (1) modular broad wall panel with recessed cyan vertical seam and dark lower skirting; (2) thick square floor panel with beveled corners and small inset grid; (3) open doorway frame with visible white opening and attached threshold; (4) waist-high control console with sloping dark blank screen; (5) repair/fabrication workbench with broad attached work slab and two sturdy supports; (6) sealed rounded rectangular cargo crate with inset handles. Soft matte grey-beige #A7A69C, dark slate #3A4D5B, worn copper #A87251, restrained cyan #22F5FF seams. Common Vael curved-corner architecture; no characters, legs under console apart from structural supports, no text, no separate loose tools. White gutters separate cells. This is a design board, NOT a model input.",
 "gullet-environment-board": "Four separated concept cells in a 2x2 board, ONE view per cell: (1) an open U-shaped inward-facing organic corridor wall segment with thick connected ribs around a smooth cold indigo inner membrane; (2) a second U-shaped wall segment with three branching ribs and a broad ledge, one continuous structure; (3) a Choir spawning pod, rooted closed mauve ovoid attached to a small integral plate, three cyan slits; (4) flat square close view of dark blue organic membrane material with restrained cyan branching veins covering only 3-6 percent area, broad calm shapes. Materials cold #253B61, muted #68648E, cyan #22F5FF lines. All ribs attached, no floating nodules, tentacles, particles or mist. White backgrounds and gutters, no scenic tunnel composition. This is a design board, NOT a model input.",
 "tallow-environment-board": "ONE isolated full Tallow Drift remote station hull, smooth asymmetric Vael orbital rest station, 40-50m long, overall width 0.45-0.58 length. Central flattened oval habitat, one clearly connected broad docking arm with a rectangular open mouth, two short attached swept service fins, small warm windows drawn as flat amber marks. Matte pale lavender-grey #ABAEC1 and midnight slate #394D65, restrained cyan #22F5FF Lattice seams. Quiet refuge silhouette distinct from Cinder Halo's circular ring or any ship: one static station mass, no propulsion flare. Single orthographic three-quarter front view, every part fully inside canvas. No planet, stars, base, ground, labels or detached satellites.",
}

def build():
    catalog = ROOT / "docs/art/design-catalog.json"
    old = {r['id']:r for r in json.loads(catalog.read_text(encoding='utf-8'))} if catalog.exists() else {}
    rows = []
    for name, description in NPCS.items():
        rows.append(dict(id=name, category="npc", mesh_input=True, prompt="\n".join([STYLE, SINGLE, VAEL, description, POSE]), references=["art-src/Generated/P1/refs/species-sheet-v2.png"]))
    for name, description in ENEMIES.items():
        rows.append(dict(id=name, category="enemy", mesh_input=name != "cantor", prompt="\n".join([STYLE, SINGLE, description]), references=[]))
    for name, description in SHIPS.items():
        rows.append(dict(id=name, category="ship", mesh_input=True, prompt="\n".join([STYLE, SINGLE, description, "Single orthographic three-quarter front view, 30 degrees above, complete length and silhouette, head/cockpit aligned with hull. White gaps between prongs/vanes while all roots stay attached."]), references=[]))
    for name, description in ENV.items():
        rows.append(dict(id=name, category="environment", mesh_input=name == "tallow-environment-board", prompt="\n".join([STYLE, description]), references=[]))
    folder = ROOT / "art-src/Generated/P1-production/refs"
    folder.mkdir(parents=True, exist_ok=True)
    for row in rows:
        for key in ('accepted_source','qa'):
            if key in old.get(row['id'],{}): row[key]=old[row['id']][key]
        row["source"] = f"art-src/Generated/P1-production/refs/{row['id']}.png"
        row["prompt_path"] = f"docs/art/prompts/{row['id']}.md"
        (ROOT / row["prompt_path"]).write_text(row["prompt"] + "\n", encoding="utf-8")
        (folder / f"{row['id']}.prompt.txt").write_text(row["prompt"] + "\n", encoding="utf-8")
    (ROOT / "docs/art/design-catalog.json").write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(rows))

if __name__ == "__main__":
    build()
