"""Versioned P1 image prompts. Generation uses the session's built-in image tool."""
from pathlib import Path
R=Path(__file__).resolve().parents[1]
out=R/'art-src/Generated/P1/refs'
out.mkdir(parents=True,exist_ok=True)
anatomy='''The Vael are likeable unmistakably alien plantigrade bipeds, 1.80-2.00 metres tall, elegant long limbs and sturdy shoulders, mature believable bodies at 7.2-7.8 head heights. Forearm length 1.06-1.12 times upper arm. Four fingers and one thumb per hand, no tail. Smooth matte slate-blue to warm-grey skin; the lighter colour is limited to face, throat and palms. Cranium slightly elongated swept backwards, length 1.12-1.22 times ordinary human cranium; NO HAIR, NO EXTERNAL EARS. Low sensory ridge behind the jaw, small soft low-bridge nose, normal closed relaxed mouth with slightly darker lips. Large almond eyes with bright ring irises and clearly pale sclera. A crown-to-back-of-skull crest of flat overlapping keratin feather-like FRONDS, clearly shaped as broad plumes rather than strands of hair. Male plumes shorter and thicker swept back; broader shoulders 2.45-2.70 head widths and a square jaw. Female plumes longer finer and falling just past shoulders; shoulder width 2.05-2.30 head widths, narrower face and higher cheek ridge. Both sexes same adult height range. No extreme waist or bust; waist is 0.82-0.94 of hip width. The identity feature is thin branching under-skin SYNC-LINES: temple to jaw hinge, collarbones to sternum, elbows down forearms onto hands, knees down shins. Male lines bolder and fewer, female finer and more branching.'''
natural='''Natural form wears muted layered asymmetric wraps and a sash over a fitted underlayer, modest practical civilian clothing, one accent colour. Arms have areas of bare skin where the filaments are visible. The only visible tech is a small metal collar node at base of neck, wrist bands and a spine plate above collar. Plumes remain exposed.'''
shaped='''Shaped form: the SAME person's face, crest, build and height remain recognizable. Living metal flows from collar/wrist/spine docking nodes into matte segmented forearm, shin, shoulder and chest plates. Angular swept collar, a light translucent visor across eyes, thin metal ribs SHEATH the existing plume fronds. Wrist light blade attached on main right hand, forearm emitter attached on left. Four separated back vanes folded beside spine. No detached parts. Sync lines brighter but still one flat key colour with no lighting bloom.'''
qa='''Flat white #FFFFFF background to every edge. Crisp flat cel-shaded anime concept illustration, clean deliberate colour blocks and economical thin dark outlines, only two flat tonal steps per material. No gradients pretending to be metal reflections. No gloss, specular, reflections, rim light, cast shadows or ground shadows. No ground, scenery, particles, mist, props, text, labels, numbers, logos, watermark or border. Heads aligned with torso axes. White visible continuously between arms and trunk, between each pair of legs down to the feet; hands relaxed open and fingers visibly separated. All appendages rooted in the body; no floating pieces. Entire figures and crest tips fit with 5-8 percent white margin.'''
prompts={
'species-sheet':f'''Use case: stylized-concept. A wide species design sheet with FOUR full-body figures in ONE horizontal row, separated by broad white columns 0.5-0.7 head widths. Left to right: Vael male Natural, Vael female Natural, Vael male Shaped, Vael female Flight. Each is one frontal view only, no repeated angles. {anatomy} {natural} {shaped} Flight is Shaped with four thin attached thruster wings unfolded, two on each side, wing tip span 1.10-1.30 times body height, clear white gaps between wings and limbs. The fourth female's normal horizontal diving pose is presented vertically like a standing design reference: legs close but with a narrow white gap, arms held 15-20 degrees from body. In this species sheet EVERY sync filament and wing seam is the identical saturated cyan key colour #22F5FF. Muted slate and warm grey wraps with restrained rust accents. {qa}''',
'species-faces':f'''Use case: stylized-concept. A wide face detail sheet with precisely TWO large frontal shoulder-up portraits, Vael adult male left and adult female right, clear wide white gutter. {anatomy} Male slate plumes with copper tips; female pale lavender plume mane; both have cyan #22F5FF sync lines branching from temple to jaw and collarbone to sternum. Calm alert friendly eyes. Enough head and shoulder space to show whole plumes with no cropping. {natural} {qa}''',
'taren-board':f'''Use case: stylized-concept. Three-panel character design board with no borders or text: full-body Natural front view LEFT, full-body Shaped front view CENTRE, large shoulder-up Natural face close-up RIGHT. Exactly the same adult male TAREN VOSK in all three. {anatomy} Height 1.90-1.94m, heavy shoulder silhouette, steady dry curious expression, slate-grey skin #677887 with slightly lighter face #93A2AD, dark slate plumes #293847 with copper tips #C98254. Sync hue saturated amber-gold #FFB62E; every filament the same flat hue. Outfit accent copper #C98254 over charcoal #283541 and dusty sand #9C8C76 wraps. {natural} {shaped} His blade-forward silhouette has a long visible right wrist edge, blade length 0.32-0.40 body height; broad shoulder plates. Each figure has separate arms and legs with visible background. Not a soldier in a helmet: preserve alien mouth, jaw, nose, plumes and visible skin. {qa}''',
'sela-board':f'''Use case: stylized-concept. Three-panel character design board with no borders or text: full-body Natural front view LEFT, full-body Shaped front view CENTRE, large shoulder-up Natural face close-up RIGHT. Exactly the same adult female SELA IRUN in all three. {anatomy} Height 1.88-1.94m, long high crown plume silhouette, quick sharp teasing expression, cool slate-blue matte skin #718A9B with lighter face #A2B7C4. Pale violet-white keratin FRONDS #D7CFF0, visibly discrete overlapping broad feather-like blades with lilac roots #9C8DC1, never human hair. Saturated cyan #22F5FF sync lines, every filament same flat hue; lilac #AE9CCF accent sash over deep blue-grey #334756 wraps. {natural} {shaped} Emitter-forward silhouette: substantial clearly attached left forearm emitter, shorter right wrist edge at 0.18-0.24 body height. Taller plume crest and slimmer shoulders than Taren, confident practical adult proportions, no exaggerated breasts or hips. {qa}'''
}
for name,prompt in prompts.items():
    (out/(name+'.prompt.txt')).write_text(prompt+'\n',encoding='utf-8')
    docs=R/'docs/art/prompts';docs.mkdir(parents=True,exist_ok=True)
    (docs/(name+'.md')).write_text('# '+name+'\n\n'+prompt+'\n',encoding='utf-8')
print('P1_PROMPTS_READY count=4')
