"""Preserve approved production face identity while adding the Shaped equipment."""
import json
from pathlib import Path
from art_catalog import ROOT, STYLE, SINGLE, POSE
path=ROOT/'docs/art/design-catalog.json';rows=json.loads(path.read_text(encoding='utf-8'))
for who in ('taren','sela'):
 natural=next(r for r in rows if r['id']==who+'-natural')
 assert natural.get('accepted_source')
 identity=("Taren: broad blunt square-jawed face, small nose scar, hooded amber ring eyes, dark thick fronds with copper tips, broad shoulders. Amber sync #FFB62E, copper #C98254, ivory #C9C2AE armour and charcoal #283541 joints. Larger right wrist blade mount and smaller left emitter." if who=='taren' else "Sela: long angular face, raised right brow, crooked smile, three small slate speckles under left eye, cyan ring eyes, pale violet-white plume-mane. Cyan sync #22F5FF, lilac #AE9CCF accents, ivory #C8D0D3 armour and deep slate #334756 joints. LARGE left forearm emitter and smaller right wrist blade mount.")
 prompt='\n'.join([STYLE,SINGLE,"Use attached image 1 as the exact identity and proportions reference; image 2 supplies the approved Shaped palette/equipment direction. Produce exactly ONE front A-pose SHAPED form, not a board. Preserve the newer unique FACE from image 1. Vael: no external ears, no tail, no hair; flat overlapping keratin fronds, pale sclera, ring eyes, smooth matte slate skin.",identity,"Replace Natural wraps with fitted segmented Lattice armour over forearms, shins, shoulders and chest. Keep the individual face and chin visible. A narrow light visor rests across the eyes, transparent enough to see both irises; no glass reflections. Plumes sheathed in thin matte ribs. Retract the energy blade fully for the reconstruction pose: a wrist blade socket remains, but no long blade obscures fingers. Left emitter is attached to forearm and leaves the hand unobscured. No cloth skirt or waist sash.","Exactly FOUR long thin BACK VANES, all rooted on the spine plate by separate short struts: two upper vanes and two lower vanes, paired left/right. They are folded mostly parallel to the spine, tilted only 8-15 degrees outward. Upper pair rises just above the shoulders; lower pair ends near hips. All FOUR dark rigid vane bodies must be separately visible, with white strips between their outer edges and the arms/body, except their narrow rooted struts. Vane width 0.08-0.12 torso width; each vane length 0.70-0.90 torso length. No detached floating vanes, extra fins, wings merging into arms or plates extending across limb gaps.",POSE,"Five clearly separated digits per hand. Palette lines remain flat saturated marks, no bloom spill. Opaque white everywhere behind the figure."])
 name=who+'-shaped';row=dict(id=name,category='hero',mesh_input=True,character=who.title(),form='Shaped',prompt=prompt,references=[natural['accepted_source'],f'art-src/Generated/P1/refs/{who}-board'+('.png' if who=='taren' else '-v2.png')],source=f'art-src/Generated/P1-production/refs/{name}.png',prompt_path=f'docs/art/prompts/{name}.md')
 rows=[r for r in rows if r['id']!=name]+[row];(ROOT/row['prompt_path']).write_text(prompt+'\n',encoding='utf-8');(ROOT/f'art-src/Generated/P1-production/refs/{name}.prompt.txt').write_text(prompt+'\n',encoding='utf-8')
path.write_text(json.dumps(rows,indent=2)+'\n',encoding='utf-8');print(json.dumps(rows))
